# Force Field X configuration for Travis-CI

language: java

sudo: false

matrix:
  include:
    - os: linux
      jdk: oraclejdk11
    - os: linux
      jdk: oraclejdk16
    - os: osx
      osx_image: xcode12.5

cache:
  directories:
  - $HOME/.m2

notifications:
  email:
    recipients:
      michael-schnieders@uiowa.edu
    on_success: change
    on_failure: always

script: travis_wait 30 mvn test -B -DskipTests=false -Dpj.nt=2 -Dffx.log=WARNING -Dffx.test.log=WARNING

