# Force Field X configuration for Travis-CI

language: java

sudo: false

matrix:
  include:
    - os: linux
      jdk: oraclejdk8
    - os: osx
      osx_image: xcode8

cache:
  directories:
  - $HOME/.m2

script: mvn test -B -DskipTests=false -Dpj.nt=2
