# Force Field X configuration for Travis-CI

language: java

sudo: false

matrix:
  include:
    - os: linux
      jdk: oraclejdk8
    - os: osx
      osx_image: xcode8

cache:
  directories:
  - $HOME/.m2

notifications:
  email:
    recipients:
      jacob-litman@uiowa.edu
    on_success: change
    on_failure: always

script: mvn test -B -DskipTests=false -Dpj.nt=2
